CREATE TABLE user ( 
	uid VARCHAR(5) NOT NULL,
	pswd VARCHAR(45) NOT NULL,
	datetime DATETIME NOT NULL,
	role_id INTEGER NOT NULL,
	PRIMARY KEY (uid) 
	);
	
CREATE TABLE customer (
	cid VARCHAR(5) NOT NULL, 
	first_name VARCHAR(25) NOT NULL,
	last_name VARCHAR(25) NOT NULL, 
	address TEXT NOT NULL, 
	city VARCHAR(50) NOT NULL,
	state VARCHAR(50) NOT NULL, 
	pincode INTEGER NOT NULL, 
	email VARCHAR(50) NOT NULL, 
	contact VARCHAR(10) NOT NULL, 
	PRIMARY KEY (cid) 
	);
	
CREATE TABLE tarrif_plan (
	pid VARCHAR(5) NOT NULL,
	name VARCHAR(50) NOT NULL,
	tarrif_call REAL NOT NULL,
	tarrif_data REAL NOT NULL,
	validity INTEGER NOT NULL,
	rental REAL,
	PRIMARY KEY (pid)
	);
	
CREATE TABLE subscription (
	sid VARCHAR(10) NOT NULL,
	cid VARCHAR(5) NOT NULL,
	pid VARCHAR(5) NOT NULL,
	PRIMARY KEY(sid)
	);

CREATE TABLE usage (
	sid VARCHAR(10) NOT NULL,
	voice INTEGER NOT NULL,
	data INTEGER NOT NULL,
	datetime DATETIME NOT NULL
	);

CREATE TABLE employee (
	eid VARCHAR(5) NOT NULL, 
	first_name VARCHAR(25) NOT NULL,
	last_name VARCHAR(25) NOT NULL, 
	role_id INTEGER NOT NULL,
	email VARCHAR(50) NOT NULL, 
	contact VARCHAR(10) NOT NULL,
	PRIMARY KEY (eid) 
	);

CREATE TABLE role(
	rid INTEGER NOT NULL,
	role VARCHAR(50) NOT NULL,
	PRIMARY KEY(rid)
	);